language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
  - master
  
before_script:
  - cd OSS-Project-FrontEnd
  - npm install -g @angular/cli
  
script:
- ng lint
- ng build --prod
